# -*- coding: utf-8 -*-
"""AulaIA27.03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18dzer03bYaZJjH9JFyfH8PADQi3Sh7aO
"""

import pandas as pd

#Criando uma Série:
# Criando uma Série a partir de uma lista
data = [10, 20, 30, 40]
series = pd.Series(data)
print(series)

# Criando uma Série com índices personalizados
index = ['a', 'b', 'c', 'd']
series = pd.Series(data, index=index)
print(series)

# Criando um DataFrame a partir de um dicionário
data = {'Coluna1': [1, 2, 3], 'Coluna2': ['A', 'B', 'C']}
df = pd.DataFrame(data)
print(df)
print(df['Coluna2'][1])

df_csv = pd.read_csv('sujos.csv')
print(df_csv)

# Lendo um arquivo CSV com dados possivelmente sujos
df_sujos = pd.read_csv('sujos.csv')
print(df_sujos)

# Verificando os tipos de dados
print(df_sujos.dtypes)

# Convertendo a coluna 'Idade' para tipo numérico
df_sujos['idade'] = pd.to_numeric(df_sujos['idade'], errors='coerce')
print(df_sujos['idade'])

# Removendo linhas com valores ausentes na coluna 'Idade'
df_sujos.dropna(inplace=True) #remover todos simultaneamente

print(df_sujos)

# Removendo duplicados
df_sujos.drop_duplicates(inplace=True)
print(df_sujos)

# Salvando o DataFrame limpo
df_sujos.to_csv('dados_limpos.csv', index=False)